Test/#140 local daily location weather data source
Team-Weather/flutter-wea-co pull request #141
Opened 2024-05-09 11:34 UTC by NalaJang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- LocalDailyLocationWeatherDataSource 테스트 코드 작성
- Hive Wrapper 클래스 테스트

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Location, Weather, DailyLocationWeather에 toHive(), fromHive() 생성
=> DailyLocationWeather 데이터를 String으로 인코딩, 디코딩할 때 DateTime은 toIso8601String()을 사용하여 타입 변환이 필요했습니다.
=> 기존에 구현되어 있는 toJson(), fromJson()의 DateTime은 TimeStamp로 또는 TimeStamp를 DateTime로 타입 변환 역할을 하고 있어서 따로 생성하였습니다.
2. Hive 테스트를 위한 hive_test 의존성 추가
3. MockHiveWrapper 생성
4. LocalDailyLocationWeatherDataSourceImpl 테스트 코드 생성
=> Hive를 이용한 로컬에 dailyLocationWeather 데이터를 저장하고 가져오는 테스트 코드 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<img width="511" alt="image" src="https://github.com/Team-Weather/flutter-wea-co/assets/73895803/6a17982e-adec-40ba-a271-7e04c00c09eb">

- DateTime을 인코딩을 하자 위와 같은 에러가 발생했습니다. 
Dart에서는 Date를 String으로 변환하려면 `.toIso8601String()`를 사용해야한다는 것을 알았습니다.
('ISO 8601' : 날짜와 시간을 나타내는 국제 표준 형식)

```dart
DateTime now = DateTime.now();
String isoString = now.toIso8601String();
print(isoString); // 예: "2024-05-07T14:30:00.000Z"
  
DateTime now = DateTime.now();
print(now.toString()); // 예: "2024-05-07 14:30:00.000"
```

- 각 모델 클래스 Location, Weather, DailyLocationWeather의 DateTime 타입의 필드들을 toIso8601String() 또는 DateTime으로 변환해주어야 했는데, toJson(), fromJson()의 convertDateTimeToTimestamp(), convertTimestampToDateTime()에 사용되고 있었습니다. toIso8601String()와 중첩으로 사용할 수 없어서 고민하고 있었는데 팀원들에게서 `toHive()`, `fromHive()` 생성에 대한 조언을 받았습니다.
반드시 toJson(), fromJson()안에서만 변환해야한다는 고정관념에서 벗어날 수 있었습니다.

- `flutter test`를 실행하여 내가 테스트를 올바르게 했는지, 내가 바꾼 코드들이 다른 코드에 영향을 주진 않았는 지 확인할 수 있어 테스트 코드 작성의 이점을 느낄 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항

2024-05-09 12:02 UTC, hoogom88 requested changes
코멘트 확인 부탁드립니다.

2024-05-09 12:02 UTC, hoogom88 commented on test/data/weather/data_source/local_data_source/local_daily_location_weather_data_source_impl_test.dart
> +        expect(jsonEncode(actualDailyLocationWeather), hiveWrapper.mockValue);
expect(jsonEncode(dailyLocationWeather.toHive), hiveWrapper.mockValue);
이렇게 검증을 하는 것이 정확할 것 같습니다.

2024-05-10 04:11 UTC, hoogom88 approved these changes
LGTM.👍

2024-05-10 04:15 UTC, SeongJongHo approved these changes
LGTM 👍🏼

2024-05-10 04:21 UTC, KimDonghyeok approved these changes
LGTM 👍

2024-05-10 04:22 UTC, merged