Feat/#38 get edit location use case
Team-Weather/flutter-wea-co pull request #77
Opened 2024-05-02 16:45 UTC by NalaJang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- GetEditLocationUseCase 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로컬 DB에 저장된 현재 위치 정보를 요청합니다.
2. 저장된 정보가 없을 경우, geolocator를 통해 현재 위치 정보를 요청합니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2024-05-02 17:18 UTC, hoogom88 requested changes

2024-05-02 17:18 UTC, hoogom88 commented on lib/domain/location/repository/location_repository.dart
Location이 어디서(local or remote)오는 지는 캡슐화되는 것이 좋을 것 같습니다.
Future<Location?> getLocation() 하나만 public으로 외부에 노출하고, 내부적으로 로직을 처리하는 건 어떤가요

2024-05-02 17:18 UTC, hoogom88 commented on test/mock/data/location/repository/mock_location_repository_impl.dart
> +    String city = 'city',
city 값을 얻기 위한 메서드이므로 city 파라미터는 없어도 될 것 같습니다.

2024-05-02 17:18 UTC, hoogom88 commented on test/domain/location/use_case/get_edit_location_use_case_test.dart
> +        expect(actual, expectedResult);
actual의 createdAt과 expectedResult의 createdAt이 서로 다를 가능성이 있습니다.

2024-05-02 18:31 UTC, gyubit approved these changes
LGTM 👍🏼

2024-05-02 23:16 UTC, NalaJang commented on test/domain/location/use_case/get_edit_location_use_case_test.dart
> +        expect(actual, expectedResult);
geolocator 로 현재 위치 정보를 요청 시 바로 얻어 오기 때문에 동일할 것이라고 생각했습니다.
테스트 코드에서는 minute까지만 비교하는데, millisecond까지 포함한 전체를 비교했을 때는 다를 수 있습니다.
범위 제한 없이 전체 시간을 비교해야 할까요?

2024-05-03 00:12 UTC, hoogom88 commented on test/domain/location/use_case/get_edit_location_use_case_test.dart
> +        expect(actual, expectedResult);
Given에서 expectedResult를 초기화하고, mock locationRepository에 값을 넘겨주어, locationRepository.getLocation 메서드를 호출하면 해당 값을 반환하도록 하는 것이 더 정확할 것 같습니다

2024-05-03 00:13 UTC, hoogom88 commented on lib/domain/location/repository/location_repository.dart
넵넵 맞습니다. 그리고 Location을 가지고 오는 것은 DataLayer의 책임이기 때문에, 유스케이스의 입장에서 이 데이터가 어디서 오는 지 알 필요도, 관련한 책임을 가져서도 안된다고 저는 생각했습니다.

2024-05-03 01:55 UTC, hoogom88 approved these changes

2024-05-05 01:24 UTC, hoogom88 commented
LGTM👍

2024-05-05 01:25 UTC, KimDonghyeok approved these changes
LGTM 👍

2024-05-05 01:26 UTC, merged