Feat/#37 refresh user page use case
Team-Weather/flutter-wea-co pull request #80
Opened 2024-05-02 21:19 UTC by KimDonghyeok

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 특정 유저페이지에서 pull-to-refresh 했을 때 피드 목록을 새로 불러오는 유스케이스 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 유저의 email 로 피드 목록을 최신순으로 limit 갯수만큼만 불러옴
- RefreshUserPageUseCase.execute() 메소드 인자 중
  - limit 는 선택 파라미터, 기본값 20개 설정
  - createdAt 은 선택 파라미터, FeedRepository.getFeedList() 메소드 호출 시 null 전달
    (무조건 최신순으로 limit 개수만큼만 반환되도록 구현)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- MockFeedRepositoryImpl 클래스에 getFeedList() 메소드 인자 테스트용 Map 콜렉션 추가, 초기화 로직 추가

2024-05-02 23:39 UTC, NalaJang approved these changes
LGTM 👍🏻

2024-05-03 00:25 UTC, hoogom88 requested changes
미구현 된 기능이 있어, 수정 요청 드립니다.

2024-05-03 00:25 UTC, hoogom88 commented on lib/domain/feed/use_case/refresh_user_page_use_case.dart
메서드 기능 설명 주석과는 달리, 유저 프로필을 업데이트 하는 로직이 없습니다.

2024-05-03 00:25 UTC, hoogom88 commented on test/mock/data/feed/repository/mock_feed_repository_impl.dart
> +
위의 methodParameterMap을 사용하지 않고, 새롭게 선언한 이유가 있을까요?

2024-05-03 06:00 UTC, KimDonghyeok commented
> 미구현 된 기능이 있어, 수정 요청 드립니다.

수정해서 PR에 반영 되었습니다.

2024-05-04 04:33 UTC, gyubit approved these changes
LGTM 👍🏼

2024-05-04 05:16 UTC, hoogom88 approved these changes

2024-05-04 15:58 UTC, somarok approved these changes
LGTM :D

2024-05-05 01:14 UTC, merged