Feat/#4 save cropped image use case
Team-Weather/flutter-wea-co pull request #82
Opened 2024-05-03 00:58 UTC by gyubit

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 크롭된 이미지를 imagePath 값을 사용하여 저장하는 SaveCroppedImageUseCase 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 이미지 저장관련 Use case 및 test 작성
- ImageRepository를 활용하여 이미지를 저장하는 방식을 구현한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 추후 저장소(내부DB or 파이어베이스) 연관성 고려 필요.
- 추후 이미지 크롭 패키지의 종류에 따라 본 코드 사용가능 여부 검토 필요

<br />

## :: 기타 질문 및 특이 사항

2024-05-03 01:35 UTC, SeongJongHo commented on lib/domain/common/use_case/save_cropped_image_use_case.dart
> +    return _imageRepository.saveCroppedImage(imagePath);
@gyubit 이미지 저장의 반환값이 Feed인 부분이 이해가 가질 않습니다.
그리고 await이 지금상황에서는 필요는 없어보이지만 의도하신건지 궁금합니다.

2024-05-03 01:50 UTC, gyubit commented on lib/domain/common/use_case/save_cropped_image_use_case.dart
> +    return _imageRepository.saveCroppedImage(imagePath);
@SeongJongHo 이미지 저장의 반환값이 Feed인 부분은 저장된 이미지가 최종적으로 피드에서 사용된다고 이해해서 그렇게 하였습니다. 이 부분에 대한 종호님의 의견을 더 듣고 싶습니다. 별로 저장하는 모델을 구축해야하는지에 대한 고민도 해보았으나 피드가 적절하다고 판단했었습니다.
그리고 await는 의도한 것은 아닙니다. 그럼 Future와 async를 제거해도 동작상의 문제는 없는 건가요?

2024-05-05 01:59 UTC, hoogom88 commented on lib/domain/common/use_case/save_cropped_image_use_case.dart
> +    return _imageRepository.saveCroppedImage(imagePath);
@gyubit 이미지 저장을 요청하는 유스케이스이기 때문에, 반환 값은 저장 성공/실패 여부인 bool이 더 적합한 것 같습니다. 아직 크롭한 이미지로 피드를 작성하지 않은 단계이기 때문에 피드를 반환할 수도 없습니다.

2024-05-05 02:00 UTC, hoogom88 requested changes
종호님이 코멘트하신 메서드의 반환타입 부분은 수정이 필요해 보입니다.

2024-05-05 10:46 UTC, gyubit commented on lib/domain/common/use_case/save_cropped_image_use_case.dart
> +    return _imageRepository.saveCroppedImage(imagePath);
bool로 변경하였습니다.

2024-05-05 11:03 UTC, hoogom88 approved these changes

2024-05-05 11:15 UTC, NalaJang approved these changes
LGTM👍🏻

2024-05-05 11:21 UTC, merged