Feat: GetHomeWeatherUseCase 및 테스트 코드 작성
Team-Weather/flutter-wea-co pull request #85
Opened 2024-05-03 03:11 UTC by somarok

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- GetHomeWeatherUseCase 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. WeatherRepository 인터페이스에 getDailyLocationWeather 추상 메서드 추가
2. GetHomeWeatherUseCase 작성
3. GetHomeWeatherUseCase 테스트 코드 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- weatherRepository 이름이 DailyLocationWeatherRepository로 바뀌어야 할 것 같다.

2024-05-04 04:31 UTC, gyubit approved these changes

2024-05-04 04:32 UTC, gyubit commented
LGTM 👍🏼

2024-05-04 18:30 UTC, NalaJang approved these changes
LGTM👍🏻

2024-05-05 01:31 UTC, hoogom88 requested changes
유스케이스의 이름 때문에 혼동이 생긴 것 같습니다. 해당 유스케이스는 DailyLocationWeather를 요청해야 합니다. 기능 수정과 더불어 가능하시다면 유스케이스의 이름을 GetDailyLocationWeatherUseCase로 변경하는 것이 좋을 것 같습니다.

2024-05-05 04:55 UTC, somarok commented
> 유스케이스의 이름 때문에 혼동이 생긴 것 같습니다. 해당 유스케이스는 DailyLocationWeather를 요청해야 합니다. 기능 수정과 더불어 가능하시다면 유스케이스의 이름을 GetDailyLocationWeatherUseCase로 변경하는 것이 좋을 것 같습니다.

해당사항 모두 수정하여 올렸습니다. 확인 부탁드려요 :)

2024-05-05 05:23 UTC, hoogom88 approved these changes
기능은 문제 없지만, 예외 처리를 이후에 리팩토링 해야 할 것 같습니다.

2024-05-05 05:25 UTC, somarok commented
> 기능은 문제 없지만, 예외 처리를 이후에 리팩토링 해야 할 것 같습니다.

맞아요 리스폰스 모델 하나 만들어야겠어요

2024-05-05 05:25 UTC, merged