Feat/#12 get cropped image use case
Team-Weather/flutter-wea-co pull request #88
Opened 2024-05-04 05:29 UTC by gyubit

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- getCroppedImageUseCase 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- flutter CacheManager를 통해서 temporary directory에 파일 읽고(FIle) 쓰기(ByteArray)가 간단하게 가능하다는 것을 알게 되었고, 읽어오기를 시도하였습니다.

<br />

## :: 기타 질문 및 특이 사항

2024-05-04 05:46 UTC, SeongJongHo requested changes

2024-05-04 05:46 UTC, SeongJongHo commented on lib/domain/common/file/repository/file_repository.dart
> +  Future<File?> getCroppedImage({required List<int> data});
@gyubit 이부분은 데이터를 저장하는 부분이 아니기 때문에 데이터를 넘겨준다기보다는 가져오는 메소드로 보입니다. 보통 가져올때는 가져오기 위한 플래그(키, 식별자)를 넘겨주는데요 저희의 시나리오대로라면 데이터소스에서 키값이 상수로 고정되어있기때문에 파라미터가 필요 없는걸로 보입니다.

2024-05-05 11:00 UTC, gyubit commented on lib/domain/common/file/repository/file_repository.dart
> +  Future<File?> getCroppedImage({required List<int> data});
데이터 송수신에 대한 구조를 잠시 헷갈렸던 것 같습니다. 메소드에서 파라미터 제거 하였습니다.

2024-05-05 11:09 UTC, hoogom88 approved these changes
LGTM👍

2024-05-05 11:23 UTC, NalaJang approved these changes
LGTM👍🏻

2024-05-05 11:41 UTC, SeongJongHo approved these changes

2024-05-05 11:41 UTC, merged